name: AnnouncePlugin
version: 1.0
main: me.kaistudio.AnnouncePlugin
api-version: "1.21"
description: Broadcasts an announcement to all online players

permissions:
  kai.announce:
    description: Allows use of /announce
    default: op
